# Generated by Django 3.2.8 on 2021-10-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_casi_id', models.IntegerField()),
                ('song_casi_ten', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tacgia_id', models.IntegerField()),
                ('book_tacgia', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_theloai_id', models.IntegerField()),
                ('book_theloai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('hoten', models.CharField(max_length=255)),
                ('gioitinh', models.CharField(choices=[('F', 'Nu'), ('M', 'NAM'), ('A', 'Khac')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tensach', models.CharField(max_length=255)),
                ('book_quocgia', models.CharField(max_length=100)),
                ('book_noidung', models.CharField(max_length=255)),
                ('book_anhbia', models.FileField(upload_to='')),
                ('book_tomtat', models.CharField(max_length=255)),
                ('book_danhgia', models.FloatField(default=0)),
                ('book_tacgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.tacgia')),
                ('book_theloai_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.theloai')),
            ],
        ),
        migrations.CreateModel(
            name='Nhac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField()),
                ('song_tenbaihat', models.CharField(max_length=255)),
                ('song_anhbia', models.FileField(upload_to='')),
                ('song_quocgia', models.CharField(max_length=100)),
                ('song_danhgia', models.FloatField(default=0)),
                ('song_file', models.FileField(upload_to='')),
                ('song_casi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.casi')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favlist_id', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.sach')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_app.nhac')),
            ],
        ),
    ]
