# Generated by Django 3.2.8 on 2021-12-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favlist_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_Sach',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='item_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_book',
            field=models.CharField(default='', max_length=50),
        ),
    ]
