# Generated by Django 3.2.8 on 2021-12-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='book_tacgia',
        ),
    ]
