# Generated by Django 3.2.8 on 2021-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0002_remove_sach_book_tacgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='book_tacgia',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
