# Generated by Django 3.2.8 on 2021-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0002_auto_20211101_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='slug',
            field=models.SlugField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theloai',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
