# Generated by Django 3.2.8 on 2021-12-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0002_auto_20211207_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='book_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
