# Generated by Django 3.2.8 on 2021-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0003_auto_20211101_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='book_noidung',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
