# Generated by Django 3.2.8 on 2021-12-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0003_auto_20211207_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhac',
            name='song_theloai',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gioitinh',
            field=models.CharField(choices=[('F', 'Nu'), ('M', 'Nam'), ('A', 'Khac')], max_length=1, null=True),
        ),
    ]
