# Generated by Django 3.2.8 on 2021-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0004_auto_20211211_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_music', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('music_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
