# Generated by Django 3.2.8 on 2021-11-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0004_alter_sach_book_noidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='anh',
            name='avt_ten',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
