# Generated by Django 3.2.8 on 2021-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0005_anh_avt_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avt',
            field=models.FileField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
