# Generated by Django 3.2.8 on 2021-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0006_user_user_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhac',
            name='song_anhbia',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sach',
            name='book_anhbia',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Anh',
        ),
    ]
