# Generated by Django 3.2.8 on 2021-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0009_alter_sach_book_anhbia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='book_anhbia',
            field=models.ImageField(upload_to='cover_book'),
        ),
    ]
