# Generated by Django 3.2.8 on 2021-11-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0010_alter_sach_book_anhbia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhac',
            name='song_file',
            field=models.FileField(upload_to='music'),
        ),
    ]
