# Generated by Django 3.2.8 on 2021-11-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0011_alter_nhac_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casi',
            name='song_casi_id',
        ),
        migrations.RemoveField(
            model_name='nhac',
            name='song_id',
        ),
    ]
