# Generated by Django 3.2.8 on 2021-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0012_auto_20211108_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='book_luotxem',
            field=models.IntegerField(default=0),
        ),
    ]
