# Generated by Django 3.2.8 on 2021-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0013_sach_book_luotxem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_avt',
            field=models.ImageField(upload_to=''),
        ),
    ]
