# Generated by Django 3.2.8 on 2021-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0014_alter_account_user_avt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_avt',
            field=models.ImageField(upload_to='avt'),
        ),
    ]
