# Generated by Django 3.2.8 on 2021-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0015_alter_account_user_avt'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tuoi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='gioitinh',
            field=models.CharField(choices=[('F', 'Nu'), ('M', 'NAM'), ('A', 'Khac')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='hoten',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
