# Generated by Django 3.2.7 on 2021-11-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0016_auto_20211110_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_avt',
            field=models.ImageField(default='static/assets/img/default-avatar.png', upload_to='avt'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='read_app.sach')),
            ],
        ),
    ]
