# Generated by Django 3.2.8 on 2021-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0022_auto_20211124_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='book_luotxem',
            field=models.FloatField(default=0),
        ),
    ]
