# Generated by Django 3.2.8 on 2021-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0023_alter_sach_book_luotxem'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhac',
            name='book_luotnghe',
            field=models.FloatField(default=0),
        ),
    ]
