# Generated by Django 3.2.8 on 2021-11-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0024_nhac_book_luotnghe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='book_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='song_id',
            new_name='item_model',
        ),
    ]
