# Generated by Django 3.2.8 on 2021-11-29 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read_app', '0025_auto_20211130_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
