# Generated by Django 3.2.8 on 2021-11-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0026_alter_favorite_favlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item_model',
            new_name='item_name',
        ),
    ]
