# Generated by Django 3.2.8 on 2021-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0027_rename_item_model_favorite_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='item_name',
            field=models.BooleanField(),
        ),
    ]
