# Generated by Django 3.2.7 on 2021-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0029_rename_item_name_favorite_is_sach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sach',
            name='book_tomtat',
            field=models.TextField(),
        ),
    ]
