# Generated by Django 3.2.8 on 2021-12-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_app', '0030_auto_20211130_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=' ', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
